export const INIT_CATALOG = 'CATALOG/INIT_CATALOG'
export const SHOW_CATALOG = 'CATALOG/SHOW_CATALOG';
export const HIDE_CATALOG = 'CATALOG/HIDE_CATALOG';
export const FETCH_PRODUCTS = 'CATALOG/FETCH_PRODUCTS';
export const ADD_PRODUCT_ON_MAP = 'CATALOG/ADD_PRODUCT_ON_MAP';
export const REMOVE_PRODUCT_FROM_MAP = 'CATALOG/REMOVE_PRODUCT_FROM_MAP';
export const UPDATE_SELECTED_PRODUCTS = 'CATALOG/UPDATE_SELECTED_PRODUCTS';

